version: 1

input:
  # video: ./data/21062025_Lipa_WFC_P1_Mosaic_StereoL.MOV
# 
output:
  base_dir: ./_tmp_out
  images_dir: images
  features_dir: features
  csv: frames.csv
  yaml: summary.yaml
  log: run.log

processing:
  feature_type: KAZE
  image_format: png
  overlap_threshold: 0.75
  max_skipped_frames: 5
  apply_enhancement: true
  create_output_dirs: true
  enable_logging: true
  # overlap_mode: FEATURE  # (optional, harmless for now)

enhance:
  enable: true
  sequence:
    - type: contrast
      alpha: 1.5
      beta: 10
    - type: grayworld
    - type: gamma
      value: 1.05
    - type: clahe
      clip_limit: 2.0
      tile_grid: [8, 8]
      space: YCrCb   # YCrCb | HSV | Lab | BGR
