name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run:  sudo apt install libopencv-dev
    - name: CMake
      run: |
        cd ${{ github.workspace }}
        mkdir -p build
        cd build
        cmake ..
    - name: Building target
      run: |
        cd build
        make
